spring.application.name=ManipReqEtRespHttpWithSpring
spring.datasource.url=jdbc:postgresql://localhost5432/ReqEtRespManip_db
spring.datasource.username=ReqEtRespManip_manager
spring.datasource.password=123456